/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package org.mozkito.versions.model;

import javax.persistence.metamodel.SetAttribute;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=org.mozkito.versions.model.Branch.class)
@javax.annotation.Generated
(value="org.apache.openjpa.persistence.meta.AnnotationProcessor6",date="Fri Jan 11 12:37:39 CET 2013")
public class Branch_ {
    public static volatile SingularAttribute<Branch,ChangeSet> head;
    public static volatile SetAttribute<Branch,String> mergedIn;
    public static volatile SingularAttribute<Branch,String> name;
}
