/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package org.mozkito.versions.model;

import java.util.Date;
import javax.persistence.metamodel.CollectionAttribute;
import javax.persistence.metamodel.MapAttribute;
import javax.persistence.metamodel.SetAttribute;
import javax.persistence.metamodel.SingularAttribute;
import org.mozkito.persistence.model.PersonContainer;

@javax.persistence.metamodel.StaticMetamodel
(value=org.mozkito.versions.model.ChangeSet.class)
@javax.annotation.Generated
(value="org.apache.openjpa.persistence.meta.AnnotationProcessor6",date="Fri Jan 11 12:37:39 CET 2013")
public class ChangeSet_ {
    public static volatile SingularAttribute<ChangeSet,Boolean> atomic;
    public static volatile MapAttribute<ChangeSet,String,Long> branchIndices;
    public static volatile SingularAttribute<ChangeSet,org.mozkito.versions.model.ChangeSet> branchParent;
    public static volatile SetAttribute<ChangeSet,org.mozkito.versions.model.ChangeSet> children;
    public static volatile SingularAttribute<ChangeSet,String> id;
    public static volatile SingularAttribute<ChangeSet,Date> javaTimestamp;
    public static volatile SingularAttribute<ChangeSet,org.mozkito.versions.model.ChangeSet> mergeParent;
    public static volatile SingularAttribute<ChangeSet,String> message;
    public static volatile SingularAttribute<ChangeSet,String> originalId;
    public static volatile SingularAttribute<ChangeSet,PersonContainer> persons;
    public static volatile CollectionAttribute<ChangeSet,Revision> revisions;
    public static volatile SetAttribute<ChangeSet,String> tags;
    public static volatile SingularAttribute<ChangeSet,VersionArchive> versionArchive;
}
