/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package org.mozkito.versions.model;

import javax.persistence.metamodel.MapAttribute;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=org.mozkito.versions.model.Handle.class)
@javax.annotation.Generated
(value="org.apache.openjpa.persistence.meta.AnnotationProcessor6",date="Thu Jan 10 17:52:36 CET 2013")
public class Handle_ {
    public static volatile SingularAttribute<Handle,VersionArchive> archive;
    public static volatile MapAttribute<Handle,RCSRevision,String> changedNames;
    public static volatile SingularAttribute<Handle,Long> generatedId;
}
