/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package org.mozkito.versions.model;

import javax.persistence.metamodel.SetAttribute;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=org.mozkito.versions.model.RCSBranch.class)
@javax.annotation.Generated
(value="org.apache.openjpa.persistence.meta.AnnotationProcessor6",date="Thu Jan 10 17:52:36 CET 2013")
public class RCSBranch_ {
    public static volatile SingularAttribute<RCSBranch,RCSTransaction> head;
    public static volatile SetAttribute<RCSBranch,String> mergedIn;
    public static volatile SingularAttribute<RCSBranch,String> name;
}
