/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package org.mozkito.versions.model;

import javax.persistence.metamodel.MapAttribute;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=org.mozkito.versions.model.RCSFile.class)
@javax.annotation.Generated
(value="org.apache.openjpa.persistence.meta.AnnotationProcessor6",date="Thu Mar 01 23:42:05 CET 2012")
public class RCSFile_ {
    public static volatile MapAttribute<RCSFile,String,String> changedNames;
    public static volatile SingularAttribute<RCSFile,Long> generatedId;
}
