/**
 * Generated by OpenJPA MetaModel Generator Tool.
 **/

package org.mozkito.versions.model;

import javax.persistence.metamodel.SingularAttribute;

import org.mozkito.versions.elements.ChangeType;

/**
 * The Class RCSRevision_.
 */
@javax.persistence.metamodel.StaticMetamodel (value = org.mozkito.versions.model.RCSRevision.class)
@javax.annotation.Generated (value = "org.apache.openjpa.persistence.meta.AnnotationProcessor6",
                             date = "Thu Jan 10 17:52:36 CET 2013")
public class RCSRevision_ {
	
	/** The change type. */
	public static volatile SingularAttribute<RCSRevision, ChangeType>     changeType;
	
	/** The changed file. */
	public static volatile SingularAttribute<RCSRevision, Handle>         changedFile;
	
	/** The revision id. */
	public static volatile SingularAttribute<RCSRevision, Long>           revisionId;
	
	/** The transaction. */
	public static volatile SingularAttribute<RCSRevision, RCSTransaction> transaction;
}
