/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package org.mozkito.versions.model;

import javax.persistence.metamodel.SingularAttribute;
import org.mozkito.versions.elements.ChangeType;

@javax.persistence.metamodel.StaticMetamodel
(value=org.mozkito.versions.model.RCSRevision.class)
@javax.annotation.Generated
(value="org.apache.openjpa.persistence.meta.AnnotationProcessor6",date="Thu Jan 10 17:52:36 CET 2013")
public class RCSRevision_ {
    public static volatile SingularAttribute<RCSRevision,ChangeType> changeType;
    public static volatile SingularAttribute<RCSRevision,Handle> changedFile;
    public static volatile SingularAttribute<RCSRevision,Long> revisionId;
    public static volatile SingularAttribute<RCSRevision,RCSTransaction> transaction;
}
