/**
 * Generated by OpenJPA MetaModel Generator Tool.
 **/

package org.mozkito.versions.model;

import javax.persistence.metamodel.SingularAttribute;

import org.mozkito.versions.elements.ChangeType;

/**
 * The Class Revision_.
 */
@javax.persistence.metamodel.StaticMetamodel (value = org.mozkito.versions.model.Revision.class)
@javax.annotation.Generated (value = "org.apache.openjpa.persistence.meta.AnnotationProcessor6",
                             date = "Mon Jan 14 13:43:14 CET 2013")
public class Revision_ {
	
	/** The change set. */
	public static volatile SingularAttribute<Revision, ChangeSet>  changeSet;
	
	/** The change type. */
	public static volatile SingularAttribute<Revision, ChangeType> changeType;
	
	/** The changed file. */
	public static volatile SingularAttribute<Revision, Handle>     changedFile;
	
	/** The revision id. */
	public static volatile SingularAttribute<Revision, Long>       revisionId;
}
