/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package org.mozkito.versions.model;

import javax.persistence.metamodel.SingularAttribute;
import org.mozkito.versions.elements.ChangeType;

@javax.persistence.metamodel.StaticMetamodel
(value=org.mozkito.versions.model.Revision.class)
@javax.annotation.Generated
(value="org.apache.openjpa.persistence.meta.AnnotationProcessor6",date="Fri Jan 11 12:37:39 CET 2013")
public class Revision_ {
    public static volatile SingularAttribute<Revision,ChangeSet> changeSet;
    public static volatile SingularAttribute<Revision,ChangeType> changeType;
    public static volatile SingularAttribute<Revision,Handle> changedFile;
    public static volatile SingularAttribute<Revision,Long> revisionId;
}
