/*******************************************************************************
 * Copyright 2011 Kim Herzig, Sascha Just
 * 
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 * 
 * http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
 * an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations under the License.
 ******************************************************************************/
/**
 * Generated by OpenJPA MetaModel Generator Tool.
 **/

package org.mozkito.versions.model;

import java.util.Date;

import javax.persistence.metamodel.CollectionAttribute;
import javax.persistence.metamodel.MapAttribute;
import javax.persistence.metamodel.SetAttribute;
import javax.persistence.metamodel.SingularAttribute;

import org.mozkito.persistence.model.PersonContainer;

/**
 * The Class Transaction_.
 */
@javax.persistence.metamodel.StaticMetamodel (value = org.mozkito.versions.model.Transaction.class)
@javax.annotation.Generated (value = "org.apache.openjpa.persistence.meta.AnnotationProcessor6",
                             date = "Fri Mar 02 12:50:26 CET 2012")
public class Transaction_ {
	
	/** The atomic. */
	public static volatile SingularAttribute<Transaction, Boolean>                                   atomic;
	
	/** The branch indices. */
	public static volatile MapAttribute<Transaction, String, Long>                                   branchIndices;
	
	/** The branch parent. */
	public static volatile SingularAttribute<Transaction, org.mozkito.versions.model.Transaction> branchParent;
	
	/** The children. */
	public static volatile SetAttribute<Transaction, org.mozkito.versions.model.Transaction>      children;
	
	/** The id. */
	public static volatile SingularAttribute<Transaction, String>                                    id;
	
	/** The java timestamp. */
	public static volatile SingularAttribute<Transaction, Date>                                      javaTimestamp;
	
	/** The merge parent. */
	public static volatile SingularAttribute<Transaction, org.mozkito.versions.model.Transaction> mergeParent;
	
	/** The message. */
	public static volatile SingularAttribute<Transaction, String>                                    message;
	
	/** The original id. */
	public static volatile SingularAttribute<Transaction, String>                                    originalId;
	
	/** The persons. */
	public static volatile SingularAttribute<Transaction, PersonContainer>                           persons;
	
	/** The revisions. */
	public static volatile CollectionAttribute<Transaction, Revision>                             revisions;
	
	/** The tags. */
	public static volatile SetAttribute<Transaction, String>                                         tags;
}
