/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package org.mozkito.versions.model;

import javax.persistence.metamodel.MapAttribute;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=org.mozkito.versions.model.VersionArchive.class)
@javax.annotation.Generated
(value="org.apache.openjpa.persistence.meta.AnnotationProcessor6",date="Fri Jan 11 12:37:39 CET 2013")
public class VersionArchive_ {
    public static volatile MapAttribute<VersionArchive,String,ChangeSet> changeSets;
    public static volatile SingularAttribute<VersionArchive,Long> generatedId;
}
