/**
 * Generated by OpenJPA MetaModel Generator Tool.
 **/

package de.unisaarland.cs.st.moskito.rcs.model;

import javax.persistence.metamodel.SetAttribute;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel (value = de.unisaarland.cs.st.moskito.rcs.model.RCSBranch.class)
@javax.annotation.Generated (value = "org.apache.openjpa.persistence.meta.AnnotationProcessor6",
                             date = "Thu Jan 26 23:21:00 CET 2012")
public class RCSBranch_ {
	
	public static volatile SingularAttribute<RCSBranch, RCSTransaction>                                   head;
	public static volatile SetAttribute<RCSBranch, String>                                                mergedIn;
	public static volatile SingularAttribute<RCSBranch, String>                                           name;
	public static volatile SingularAttribute<RCSBranch, de.unisaarland.cs.st.moskito.rcs.model.RCSBranch> parent;
}
