/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package de.unisaarland.cs.st.moskito.rcs.model;

import javax.persistence.metamodel.SetAttribute;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=de.unisaarland.cs.st.moskito.rcs.model.RCSBranch.class)
@javax.annotation.Generated
(value="org.apache.openjpa.persistence.meta.AnnotationProcessor6",date="Fri Mar 02 12:03:07 CET 2012")
public class RCSBranch_ {
    public static volatile SingularAttribute<RCSBranch,RCSTransaction> head;
    public static volatile SetAttribute<RCSBranch,String> mergedIn;
    public static volatile SingularAttribute<RCSBranch,String> name;
}
