/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package de.unisaarland.cs.st.moskito.rcs.model;

import javax.persistence.metamodel.MapAttribute;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=de.unisaarland.cs.st.moskito.rcs.model.RCSFile.class)
@javax.annotation.Generated
(value="org.apache.openjpa.persistence.meta.AnnotationProcessor6",date="Fri Sep 02 15:43:33 CEST 2011")
public class RCSFile_ {
    public static volatile MapAttribute<RCSFile,String,String> changedNames;
    public static volatile SingularAttribute<RCSFile,Long> generatedId;
}
