/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package org.mozkito.codeanalysis.model;

import javax.persistence.metamodel.ListAttribute;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=org.mozkito.codeanalysis.model.JavaMethodDefinition.class)
@javax.annotation.Generated
(value="org.apache.openjpa.persistence.meta.AnnotationProcessor6",date="Fri Mar 30 11:02:50 CEST 2012")
public class JavaMethodDefinition_ extends JavaElement_  {
    public static volatile SingularAttribute<JavaMethodDefinition,Boolean> annotatedOverride;
    public static volatile ListAttribute<JavaMethodDefinition,String> signature;
}
