/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package org.mozkito.codeanalysis.model;

import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=org.mozkito.codeanalysis.model.JavaTypeDefinition.class)
@javax.annotation.Generated
(value="org.apache.openjpa.persistence.meta.AnnotationProcessor6",date="Fri Mar 30 11:02:50 CEST 2012")
public class JavaTypeDefinition_ extends JavaElement_  {
    public static volatile SingularAttribute<JavaTypeDefinition,Boolean> anonymClass;
    public static volatile SingularAttribute<JavaTypeDefinition,Boolean> interfaze;
    public static volatile SingularAttribute<JavaTypeDefinition,org.mozkito.codeanalysis.model.JavaTypeDefinition> parent;
    public static volatile SingularAttribute<JavaTypeDefinition,String> superClassName;
}
