CREATE OR REPLACE FUNCTION public.elementChangesBetween(int, timestamp, timestamp)
 RETURNS setof changeset AS $$
  select * from changeset WHERE id IN (select r.transaction_id from javaelementlocation l JOIN javachangeoperation o ON l.id = o.changedelementlocation_id JOIN revision r ON o.revision_revisionid=r.revisionid where l.element_generatedid = $1) AND timestamp < $2 AND timestamp >= $3 ORDER BY timestamp;
$$ language sql;
