/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package org.mozkito.issues.tracker.model;


import java.util.Date;
import javax.persistence.metamodel.SingularAttribute;
import org.joda.time.DateTime;
import org.mozkito.persistence.model.PersonContainer;

@javax.persistence.metamodel.StaticMetamodel
(value=org.mozkito.issues.tracker.model.AttachmentEntry.class)
@javax.annotation.Generated
(value="org.apache.openjpa.persistence.meta.AnnotationProcessor6",date="Mon May 07 15:41:49 CEST 2012")
public class AttachmentEntry_ {
    public static volatile SingularAttribute<AttachmentEntry,DateTime> deltaTS;
    public static volatile SingularAttribute<AttachmentEntry,String> description;
    public static volatile SingularAttribute<AttachmentEntry,String> filename;
    public static volatile SingularAttribute<AttachmentEntry,String> id;
    public static volatile SingularAttribute<AttachmentEntry,Date> javaTimestamp;
    public static volatile SingularAttribute<AttachmentEntry,String> link;
    public static volatile SingularAttribute<AttachmentEntry,String> mime;
    public static volatile SingularAttribute<AttachmentEntry,PersonContainer> personContainer;
    public static volatile SingularAttribute<AttachmentEntry,Long> size;
}
