/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package org.mozkito.issues.tracker.model;


import java.util.Date;
import javax.persistence.metamodel.SingularAttribute;

import org.mozkito.persistence.model.PersonContainer;

@javax.persistence.metamodel.StaticMetamodel
(value=org.mozkito.issues.tracker.model.Comment.class)
@javax.annotation.Generated
(value="org.apache.openjpa.persistence.meta.AnnotationProcessor6",date="Mon May 07 15:41:49 CEST 2012")
public class Comment_ {
    public static volatile SingularAttribute<Comment,Report> bugReport;
    public static volatile SingularAttribute<Comment,Long> generatedId;
    public static volatile SingularAttribute<Comment,Integer> id;
    public static volatile SingularAttribute<Comment,Date> javaTimestamp;
    public static volatile SingularAttribute<Comment,String> message;
    public static volatile SingularAttribute<Comment,PersonContainer> personContainer;
}
