/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package org.mozkito.issues.tracker.model;


import javax.persistence.metamodel.SingularAttribute;

import org.mozkito.issues.tracker.elements.Type;

@javax.persistence.metamodel.StaticMetamodel
(value=org.mozkito.issues.tracker.model.EnhancedReport.class)
@javax.annotation.Generated
(value="org.apache.openjpa.persistence.meta.AnnotationProcessor6",date="Mon May 07 15:41:49 CEST 2012")
public class EnhancedReport_ {
    public static volatile SingularAttribute<EnhancedReport,Type> classifiedType;
    public static volatile SingularAttribute<EnhancedReport,Type> predictedType;
    public static volatile SingularAttribute<EnhancedReport,Report> report;
}
