/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package org.mozkito.issues.tracker.model;

import javax.persistence.metamodel.SetAttribute;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=org.mozkito.issues.tracker.model.History.class)
@javax.annotation.Generated
(value="org.apache.openjpa.persistence.meta.AnnotationProcessor6",date="Mon May 07 15:41:49 CEST 2012")
public class History_ {
    public static volatile SingularAttribute<History,String> bugId;
    public static volatile SetAttribute<History,HistoryElement> elements;
    public static volatile SingularAttribute<History,Long> id;
}
