/**
 * Generated by OpenJPA MetaModel Generator Tool.
 **/

package org.mozkito.issues.tracker.model;

import java.util.Date;

import javax.persistence.metamodel.ListAttribute;
import javax.persistence.metamodel.SetAttribute;
import javax.persistence.metamodel.SingularAttribute;

import org.mozkito.issues.tracker.elements.Priority;
import org.mozkito.issues.tracker.elements.Resolution;
import org.mozkito.issues.tracker.elements.Severity;
import org.mozkito.issues.tracker.elements.Status;
import org.mozkito.issues.tracker.elements.Type;
import org.mozkito.persistence.model.PersonContainer;


@javax.persistence.metamodel.StaticMetamodel (value = org.mozkito.issues.tracker.model.Report.class)
@javax.annotation.Generated (value = "org.apache.openjpa.persistence.meta.AnnotationProcessor6",
                             date = "Mon May 07 15:41:49 CEST 2012")
public class Report_ {
	
	public static volatile ListAttribute<Report, AttachmentEntry>     attachmentEntries;
	public static volatile SingularAttribute<Report, String>          category;
	public static volatile SetAttribute<Report, Comment>              comments;
	public static volatile SingularAttribute<Report, String>          component;
	public static volatile SingularAttribute<Report, Date>            creationJavaTimestamp;
	public static volatile SingularAttribute<Report, String>          description;
	public static volatile SingularAttribute<Report, byte[]>          hash;
	public static volatile SingularAttribute<Report, History>         history;
	public static volatile SingularAttribute<Report, String>          id;
	public static volatile SetAttribute<Report, String>               keywords;
	public static volatile SingularAttribute<Report, Date>            lastFetchJava;
	public static volatile SingularAttribute<Report, Date>            lastUpdateJavaTimestamp;
	public static volatile SingularAttribute<Report, PersonContainer> personContainer;
	public static volatile SingularAttribute<Report, Priority>        priority;
	public static volatile SingularAttribute<Report, String>          product;
	public static volatile SingularAttribute<Report, Resolution>      resolution;
	public static volatile SingularAttribute<Report, Date>            resolutionJavaTimestamp;
	public static volatile SingularAttribute<Report, String>          scmFixVersion;
	public static volatile SingularAttribute<Report, Severity>        severity;
	public static volatile SetAttribute<Report, String>               siblings;
	public static volatile SingularAttribute<Report, Status>          status;
	public static volatile SingularAttribute<Report, String>          subject;
	public static volatile SingularAttribute<Report, String>          summary;
	public static volatile SingularAttribute<Report, Type>            type;
	public static volatile SingularAttribute<Report, String>          version;
}
