/**
 * Generated by OpenJPA MetaModel Generator Tool.
 **/

package de.unisaarland.cs.st.reposuite.mapping.model;

import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel (value = de.unisaarland.cs.st.reposuite.mapping.model.MappingEngineFeature.class)
@javax.annotation.Generated (value = "org.apache.openjpa.persistence.meta.AnnotationProcessor6",
                             date = "Fri Sep 02 15:37:56 CEST 2011")
public class MappingEngineFeature_ {
	
	public static volatile SingularAttribute<MappingEngineFeature, Double> confidence;
	public static volatile SingularAttribute<MappingEngineFeature, String> fqClassName;
	public static volatile SingularAttribute<MappingEngineFeature, String> fromFieldName;
	public static volatile SingularAttribute<MappingEngineFeature, String> fromSubstring;
	public static volatile SingularAttribute<MappingEngineFeature, String> toFieldName;
	public static volatile SingularAttribute<MappingEngineFeature, String> toSubstring;
}
