/**
 * Generated by OpenJPA MetaModel Generator Tool.
 **/

package org.mozkito.persistence.model;

import java.util.Date;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel (value = org.mozkito.persistence.model.DateTimeTuple.class)
@javax.annotation.Generated (value = "org.apache.openjpa.persistence.meta.AnnotationProcessor6",
                             date = "Fri Sep 02 15:41:15 CEST 2011")
public class DateTimeTuple_ {
	
	public static volatile SingularAttribute<DateTimeTuple, Date> javaNewValue;
	public static volatile SingularAttribute<DateTimeTuple, Date> javaOldValue;
}
