/**
 * Generated by OpenJPA MetaModel Generator Tool.
 **/

package org.mozkito.persistence.model;

import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel (value = org.mozkito.persistence.model.PersonTuple.class)
@javax.annotation.Generated (value = "org.apache.openjpa.persistence.meta.AnnotationProcessor6",
                             date = "Fri Sep 02 15:41:15 CEST 2011")
public class PersonTuple_ {
	
	public static volatile SingularAttribute<PersonTuple, PersonContainer> newValue;
	public static volatile SingularAttribute<PersonTuple, PersonContainer> oldValue;
}
