/**
 * Generated by OpenJPA MetaModel Generator Tool.
 **/

package org.mozkito.persistence.model;

import javax.persistence.metamodel.MapAttribute;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel (value = org.mozkito.persistence.model.PersonContainer.class)
@javax.annotation.Generated (value = "org.apache.openjpa.persistence.meta.AnnotationProcessor6",
                             date = "Fri Sep 02 15:41:15 CEST 2011")
public class PersonContainer_ {
	
	public static volatile SingularAttribute<PersonContainer, Long>      generatedId;
	public static volatile MapAttribute<PersonContainer, String, Person> map;
}
