/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package de.unisaarland.cs.st.reposuite.persistence.model;

import javax.persistence.metamodel.SetAttribute;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=de.unisaarland.cs.st.reposuite.persistence.model.Person.class)
@javax.annotation.Generated
(value="org.apache.openjpa.persistence.meta.AnnotationProcessor6",date="Fri Sep 02 14:46:57 CEST 2011")
public class Person_ {
    public static volatile SetAttribute<Person,String> emailAddresses;
    public static volatile SetAttribute<Person,String> fullnames;
    public static volatile SingularAttribute<Person,Long> generatedId;
    public static volatile SetAttribute<Person,String> usernames;
}
