/**
 * Generated by OpenJPA MetaModel Generator Tool.
 **/

package de.unisaarland.cs.st.moskito.bugs.tracker.model;

import de.unisaarland.cs.st.moskito.persistence.model.PersonContainer;

import java.util.Date;
import javax.persistence.metamodel.SingularAttribute;
import org.joda.time.DateTime;

@javax.persistence.metamodel.StaticMetamodel (value = de.unisaarland.cs.st.moskito.bugs.tracker.model.AttachmentEntry.class)
@javax.annotation.Generated (value = "org.apache.openjpa.persistence.meta.AnnotationProcessor6",
                             date = "Fri Sep 02 15:26:32 CEST 2011")
public class AttachmentEntry_ {
	
	public static volatile SingularAttribute<AttachmentEntry, DateTime>        deltaTS;
	public static volatile SingularAttribute<AttachmentEntry, String>          description;
	public static volatile SingularAttribute<AttachmentEntry, String>          filename;
	public static volatile SingularAttribute<AttachmentEntry, String>          id;
	public static volatile SingularAttribute<AttachmentEntry, Date>            javaTimestamp;
	public static volatile SingularAttribute<AttachmentEntry, String>          link;
	public static volatile SingularAttribute<AttachmentEntry, String>          mime;
	public static volatile SingularAttribute<AttachmentEntry, PersonContainer> personContainer;
	public static volatile SingularAttribute<AttachmentEntry, Long>            size;
}
