/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package de.unisaarland.cs.st.moskito.bugs.tracker.model;

import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=de.unisaarland.cs.st.moskito.bugs.tracker.model.CommentPrimaryKey.class)
@javax.annotation.Generated
(value="org.apache.openjpa.persistence.meta.AnnotationProcessor6",date="Tue Feb 28 13:12:49 CET 2012")
public class CommentPrimaryKey_ {
    public static volatile SingularAttribute<CommentPrimaryKey,Integer> commentId;
    public static volatile SingularAttribute<CommentPrimaryKey,Long> reportId;
}
