/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package de.unisaarland.cs.st.moskito.bugs.tracker.model;

import de.unisaarland.cs.st.moskito.persistence.model.PersonContainer;
import java.util.Date;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=de.unisaarland.cs.st.moskito.bugs.tracker.model.Comment.class)
@javax.annotation.Generated
(value="org.apache.openjpa.persistence.meta.AnnotationProcessor6",date="Fri Apr 27 13:28:52 CEST 2012")
public class Comment_ {
    public static volatile SingularAttribute<Comment,Report> bugReport;
    public static volatile SingularAttribute<Comment,Long> generatedId;
    public static volatile SingularAttribute<Comment,Integer> id;
    public static volatile SingularAttribute<Comment,Date> javaTimestamp;
    public static volatile SingularAttribute<Comment,String> message;
    public static volatile SingularAttribute<Comment,PersonContainer> personContainer;
}
