/**
 * Generated by OpenJPA MetaModel Generator Tool.
 **/

package de.unisaarland.cs.st.moskito.bugs.tracker.model;

import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel (value = de.unisaarland.cs.st.moskito.bugs.tracker.model.CommentPrimaryKey.class)
@javax.annotation.Generated (value = "org.apache.openjpa.persistence.meta.AnnotationProcessor6",
                             date = "Fri Sep 02 15:26:32 CEST 2011")
public class CommentPrimaryKey_ {
	
	public static volatile SingularAttribute<CommentPrimaryKey, Integer> commentId;
	public static volatile SingularAttribute<CommentPrimaryKey, Long>    reportId;
}
