/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package de.unisaarland.cs.st.moskito.bugs.tracker.model;

import de.unisaarland.cs.st.moskito.persistence.model.DateTimeTuple;
import de.unisaarland.cs.st.moskito.persistence.model.EnumTuple;
import de.unisaarland.cs.st.moskito.persistence.model.PersonContainer;
import de.unisaarland.cs.st.moskito.persistence.model.PersonTuple;
import de.unisaarland.cs.st.moskito.persistence.model.StringTuple;
import java.util.Date;
import javax.persistence.metamodel.MapAttribute;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=de.unisaarland.cs.st.moskito.bugs.tracker.model.HistoryElement.class)
@javax.annotation.Generated
(value="org.apache.openjpa.persistence.meta.AnnotationProcessor6",date="Mon May 07 15:41:49 CEST 2012")
public class HistoryElement_ {
    public static volatile SingularAttribute<HistoryElement,String> bugId;
    public static volatile MapAttribute<HistoryElement,String,DateTimeTuple> changedDateValues;
    public static volatile MapAttribute<HistoryElement,String,EnumTuple> changedEnumValues;
    public static volatile MapAttribute<HistoryElement,String,PersonTuple> changedPersonValues;
    public static volatile MapAttribute<HistoryElement,String,StringTuple> changedStringValues;
    public static volatile SingularAttribute<HistoryElement,Long> id;
    public static volatile SingularAttribute<HistoryElement,Date> javaTimestamp;
    public static volatile SingularAttribute<HistoryElement,PersonContainer> personContainer;
}
