/**
 * Generated by OpenJPA MetaModel Generator Tool.
 **/

package de.unisaarland.cs.st.mozkito.mappings.model;

import javax.persistence.metamodel.CollectionAttribute;
import javax.persistence.metamodel.MapAttribute;
import javax.persistence.metamodel.SingularAttribute;

/**
 * The Class Relation_.
 */
@javax.persistence.metamodel.StaticMetamodel (value = de.unisaarland.cs.st.mozkito.mappings.model.Relation.class)
@javax.annotation.Generated (value = "org.apache.openjpa.persistence.meta.AnnotationProcessor6",
                             date = "Wed Jan 18 19:05:50 CET 2012")
public class Relation_ {
	
	/** The class1. */
	public static volatile SingularAttribute<Relation, String>     class1;
	
	/** The class2. */
	public static volatile SingularAttribute<Relation, String>     class2;
	
	/** The features. */
	public static volatile CollectionAttribute<Relation, Feature>  features;
	
	/** The from id. */
	public static volatile SingularAttribute<Relation, String>     fromId;
	
	/** The strategies. */
	public static volatile MapAttribute<Relation, String, Boolean> strategies;
	
	/** The to id. */
	public static volatile SingularAttribute<Relation, String>     toId;
}
