/***********************************************************************************************************************
 * Copyright 2011 Kim Herzig, Sascha Just
 * 
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 * 
 * http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
 * an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations under the License.
 **********************************************************************************************************************/
package org.mozkito.mappings.model;

import java.util.HashSet;
import java.util.LinkedList;
import java.util.Set;

import javax.persistence.ElementCollection;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.ManyToOne;
import javax.persistence.Transient;

import net.ownhero.dev.kanuni.conditions.Condition;

import org.mozkito.mappings.elements.CandidateId;
import org.mozkito.mappings.finder.Finder;
import org.mozkito.mappings.selectors.Selector;
import org.mozkito.persistence.Annotated;
import org.mozkito.persistence.PersistenceUtil;
import org.mozkito.utilities.datastructures.Tuple;

/**
 * This class represents a potential mapping pair and thus encapsulates to {@link org.mozkito.persistence.Entity}s.
 * {@link Candidate}s are generated by the {@link Finder} class using
 * {@link Finder#getCandidates(org.mozkito.persistence.Entity, Class, PersistenceUtil)}.
 * 
 * @author Sascha Just <sascha.just@mozkito.org>
 * 
 */
@Entity
@IdClass (CandidateId.class)
public class Candidate implements Annotated {
	
	/** The Constant serialVersionUID. */
	private static final long              serialVersionUID = 1464864624834219097L;
	
	/** the entity under subject. */
	private org.mozkito.persistence.Entity from;
	
	/** The preselectors. */
	private Set<String>                    selectors        = new HashSet<String>();
	
	/** a potential target. */
	private org.mozkito.persistence.Entity to;
	
	/**
	 * Instantiates a new candidate.
	 * 
	 * @deprecated this constructor should be used by OpenJPA only.
	 */
	@Deprecated
	public Candidate() {
		// for OpenJPA only
	}
	
	/**
	 * Instantiates a new candidate.
	 * 
	 * @param candidatePair
	 *            a {@link Tuple} representing the pair (from/to)
	 */
	public Candidate(
	        final Tuple<? extends org.mozkito.persistence.Entity, ? extends org.mozkito.persistence.Entity> candidatePair) {
		setFrom(candidatePair.getFirst());
		setTo(candidatePair.getSecond());
	}
	
	/*
	 * (non-Javadoc)
	 * @see org.mozkito.mappings.model.ICandidate#addSelector(org.mozkito.mappings.selectors.Selector)
	 */
	/**
	 * Adds the selector.
	 * 
	 * @param selector
	 *            the selector
	 * @return true, if successful
	 */
	@Transient
	public boolean addSelector(final Selector selector) {
		return getSelectors().add(selector.getClassName());
	}
	
	/**
	 * Adds the selectors.
	 * 
	 * @param selectors
	 *            the selectors
	 */
	@Transient
	public void addSelectors(final Set<Selector> selectors) {
		// PRECONDITIONS
		
		try {
			for (final Selector selector : selectors) {
				addSelector(selector);
			}
		} finally {
			// POSTCONDITIONS
		}
	}
	
	/*
	 * (non-Javadoc)
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@Override
	@Transient
	public boolean equals(final Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		final Candidate other = (Candidate) obj;
		if (getFrom() == null) {
			if (other.getFrom() != null) {
				return false;
			}
		} else if (!getFrom().equals(other.getFrom())) {
			return false;
		}
		if (getTo() == null) {
			if (other.getTo() != null) {
				return false;
			}
		} else if (!getTo().equals(other.getTo())) {
			return false;
		}
		return true;
	}
	
	/**
	 * Gets the simple name of the class.
	 * 
	 * @return the simple name of the class.
	 */
	@Override
	@Transient
	public final String getClassName() {
		// PRECONDITIONS
		
		final StringBuilder builder = new StringBuilder();
		
		try {
			final LinkedList<Class<?>> list = new LinkedList<Class<?>>();
			Class<?> clazz = getClass();
			list.add(clazz);
			
			while ((clazz = clazz.getEnclosingClass()) != null) {
				list.addFirst(clazz);
			}
			
			for (final Class<?> c : list) {
				if (builder.length() > 0) {
					builder.append('.');
				}
				
				builder.append(c.getSimpleName());
			}
			
			return builder.toString();
		} finally {
			// POSTCONDITIONS
			Condition.notNull(builder,
			                  "Local variable '%s' in '%s:%s'.", "builder", getClass().getSimpleName(), "getHandle()"); //$NON-NLS-1$ //$NON-NLS-2$ //$NON-NLS-3$
		}
	}
	
	/*
	 * (non-Javadoc)
	 * @see org.mozkito.mappings.model.ICandidate#getFrom()
	 */
	/**
	 * Gets the from.
	 * 
	 * @return the from
	 */
	@Id
	@ManyToOne (fetch = FetchType.EAGER, cascade = {})
	public org.mozkito.persistence.Entity getFrom() {
		return this.from;
	}
	
	/**
	 * Gets the selectors.
	 * 
	 * @return the votingSelectors
	 */
	@ElementCollection
	public Set<String> getSelectors() {
		
		return this.selectors;
		
	}
	
	/**
	 * Gets the to.
	 * 
	 * @return the to
	 */
	@Id
	@ManyToOne (fetch = FetchType.EAGER, cascade = {})
	public org.mozkito.persistence.Entity getTo() {
		return this.to;
	}
	
	/*
	 * (non-Javadoc)
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	@Transient
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = (prime * result) + ((getFrom() == null)
		                                                ? 0
		                                                : getFrom().hashCode());
		result = (prime * result) + ((getTo() == null)
		                                              ? 0
		                                              : getTo().hashCode());
		return result;
	}
	
	/**
	 * Sets the from.
	 * 
	 * @param from
	 *            the from to set
	 */
	public void setFrom(final org.mozkito.persistence.Entity from) {
		this.from = from;
		
	}
	
	/**
	 * Sets the selectors.
	 * 
	 * @param selectors
	 *            the selectors to set
	 */
	public void setSelectors(final Set<String> selectors) {
		
		this.selectors = selectors;
		
	}
	
	/**
	 * Sets the to.
	 * 
	 * @param to
	 *            the to to set
	 */
	public void setTo(final org.mozkito.persistence.Entity to) {
		this.to = to;
		
	}
	
	/*
	 * (non-Javadoc)
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		final StringBuilder builder = new StringBuilder();
		
		builder.append(getClassName());
		builder.append(" [from="); //$NON-NLS-1$
		builder.append(getFrom());
		builder.append(", to="); //$NON-NLS-1$
		builder.append(getTo());
		builder.append("]"); //$NON-NLS-1$
		return builder.toString();
	}
}
