/**
 * Generated by OpenJPA MetaModel Generator Tool.
 **/

package org.mozkito.versions.model;

import javax.persistence.metamodel.MapAttribute;
import javax.persistence.metamodel.SingularAttribute;

/**
 * The Class Handle_.
 */
@javax.persistence.metamodel.StaticMetamodel (value = org.mozkito.versions.model.Handle.class)
@javax.annotation.Generated (value = "org.apache.openjpa.persistence.meta.AnnotationProcessor6",
                             date = "Mon Jan 14 13:43:14 CET 2013")
public class Handle_ {
	
	/** The changed names. */
	public static volatile MapAttribute<Handle, Revision, String>    changedNames;
	
	/** The generated id. */
	public static volatile SingularAttribute<Handle, Long>           generatedId;
	
	/** The version archive. */
	public static volatile SingularAttribute<Handle, VersionArchive> versionArchive;
}
