/**
 * Generated by OpenJPA MetaModel Generator Tool.
 **/

package org.mozkito.versions.model;

import java.util.Date;

import javax.persistence.metamodel.MapAttribute;
import javax.persistence.metamodel.SingularAttribute;

/**
 * The Class VersionArchive_.
 */
@javax.persistence.metamodel.StaticMetamodel (value = org.mozkito.versions.model.VersionArchive.class)
@javax.annotation.Generated (value = "org.apache.openjpa.persistence.meta.AnnotationProcessor6",
                             date = "Mon Jan 14 13:43:14 CET 2013")
public class VersionArchive_ {
	
	/** The branches. */
	public static volatile MapAttribute<VersionArchive, String, Branch>    branches;
	
	/** The change sets. */
	public static volatile MapAttribute<VersionArchive, String, ChangeSet> changeSets;
	
	/** The generated id. */
	public static volatile SingularAttribute<VersionArchive, Long>         generatedId;
	
	/** The mining java date. */
	public static volatile SingularAttribute<VersionArchive, Date>         miningJavaDate;
	
	/** The mozkito hash. */
	public static volatile SingularAttribute<VersionArchive, String>       mozkitoHash;
	
	/** The mozkito version. */
	public static volatile SingularAttribute<VersionArchive, String>       mozkitoVersion;
	
	/** The used settings. */
	public static volatile SingularAttribute<VersionArchive, String>       usedSettings;
	
	/** The host info. */
	public static volatile SingularAttribute<VersionArchive, String>       hostInfo;
}
