/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package de.unisaarland.cs.st.mozkito.versions.model;

import de.unisaarland.cs.st.mozkito.versions.elements.ChangeType;

import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=de.unisaarland.cs.st.mozkito.versions.model.RCSRevision.class)
@javax.annotation.Generated
(value="org.apache.openjpa.persistence.meta.AnnotationProcessor6",date="Thu Mar 01 23:42:05 CET 2012")
public class RCSRevision_ {
    public static volatile SingularAttribute<RCSRevision,ChangeType> changeType;
    public static volatile SingularAttribute<RCSRevision,RCSFile> changedFile;
    public static volatile SingularAttribute<RCSRevision,Long> revisionId;
    public static volatile SingularAttribute<RCSRevision,RCSTransaction> transaction;
}
