/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package de.unisaarland.cs.st.moskito.mapping.mappable.model;

import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=de.unisaarland.cs.st.moskito.mapping.mappable.model.MappableEntity.class)
@javax.annotation.Generated
(value="org.apache.openjpa.persistence.meta.AnnotationProcessor6",date="Thu Nov 03 18:46:07 CET 2011")
public class MappableEntity_ {
    public static volatile SingularAttribute<MappableEntity,Long> generatedId;
    public static volatile SingularAttribute<MappableEntity,Integer> test;
}
