/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package de.unisaarland.cs.st.moskito.mapping.mappable.model;

import de.unisaarland.cs.st.moskito.bugs.tracker.model.Report;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=de.unisaarland.cs.st.moskito.mapping.mappable.model.MappableReport.class)
@javax.annotation.Generated
(value="org.apache.openjpa.persistence.meta.AnnotationProcessor6",date="Thu Nov 03 18:46:21 CET 2011")
public class MappableReport_ extends MappableEntity_  {
    public static volatile SingularAttribute<MappableReport,Report> report;
}
