/**
 * Generated by OpenJPA MetaModel Generator Tool.
 **/

package de.unisaarland.cs.st.moskito.mapping.mappable.model;

@javax.persistence.metamodel.StaticMetamodel (value = de.unisaarland.cs.st.moskito.mapping.mappable.model.MappableEnhancedReport.class)
@javax.annotation.Generated (value = "org.apache.openjpa.persistence.meta.AnnotationProcessor6",
                             date = "Thu Nov 03 18:49:03 CET 2011")
public class MappableEnhancedReport_ extends MappableEntity_ {
}
