/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package de.unisaarland.cs.st.reposuite.ppa.model;

import javax.persistence.metamodel.SetAttribute;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=de.unisaarland.cs.st.reposuite.ppa.model.JavaElementLocation.class)
@javax.annotation.Generated
(value="org.apache.openjpa.persistence.meta.AnnotationProcessor6",date="Fri Sep 02 15:42:26 CEST 2011")
public class JavaElementLocation_ {
    public static volatile SingularAttribute<JavaElementLocation,Integer> bodyStartLine;
    public static volatile SetAttribute<JavaElementLocation,Integer> commentLines;
    public static volatile SingularAttribute<JavaElementLocation,JavaElement> element;
    public static volatile SingularAttribute<JavaElementLocation,Integer> endLine;
    public static volatile SingularAttribute<JavaElementLocation,String> filePath;
    public static volatile SingularAttribute<JavaElementLocation,Long> id;
    public static volatile SingularAttribute<JavaElementLocation,Integer> position;
    public static volatile SingularAttribute<JavaElementLocation,Integer> startLine;
}
