/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package de.unisaarland.cs.st.reposuite.ppa.model;

import de.unisaarland.cs.st.reposuite.rcs.elements.ChangeType;
import de.unisaarland.cs.st.reposuite.rcs.model.RCSRevision;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=de.unisaarland.cs.st.reposuite.ppa.model.JavaChangeOperation.class)
@javax.annotation.Generated
(value="org.apache.openjpa.persistence.meta.AnnotationProcessor6",date="Fri Sep 02 15:42:26 CEST 2011")
public class JavaChangeOperation_ {
    public static volatile SingularAttribute<JavaChangeOperation,ChangeType> changeType;
    public static volatile SingularAttribute<JavaChangeOperation,JavaElementLocation> changedElementLocation;
    public static volatile SingularAttribute<JavaChangeOperation,Boolean> essential;
    public static volatile SingularAttribute<JavaChangeOperation,Long> id;
    public static volatile SingularAttribute<JavaChangeOperation,RCSRevision> revision;
}
