/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package de.unisaarland.cs.st.reposuite.ppa.model;

import javax.persistence.metamodel.ListAttribute;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=de.unisaarland.cs.st.reposuite.ppa.model.JavaMethodCall.class)
@javax.annotation.Generated
(value="org.apache.openjpa.persistence.meta.AnnotationProcessor6",date="Fri Sep 02 15:42:26 CEST 2011")
public class JavaMethodCall_ extends JavaElement_  {
    public static volatile SingularAttribute<JavaMethodCall,String> calledPackageName;
    public static volatile ListAttribute<JavaMethodCall,String> signature;
}
