/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package de.unisaarland.cs.st.mozkito.issues.tracker.model;

import de.unisaarland.cs.st.mozkito.issues.tracker.elements.Type;

import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=de.unisaarland.cs.st.mozkito.issues.tracker.model.EnhancedReport.class)
@javax.annotation.Generated
(value="org.apache.openjpa.persistence.meta.AnnotationProcessor6",date="Mon May 07 15:41:49 CEST 2012")
public class EnhancedReport_ {
    public static volatile SingularAttribute<EnhancedReport,Type> classifiedType;
    public static volatile SingularAttribute<EnhancedReport,Type> predictedType;
    public static volatile SingularAttribute<EnhancedReport,Report> report;
}
