/**
 * Generated by OpenJPA MetaModel Generator Tool.
 **/

package de.unisaarland.cs.st.moskito.ppa.model;

import javax.persistence.metamodel.ListAttribute;

@javax.persistence.metamodel.StaticMetamodel (value = de.unisaarland.cs.st.moskito.ppa.model.JavaMethodDefinition.class)
@javax.annotation.Generated (value = "org.apache.openjpa.persistence.meta.AnnotationProcessor6",
                             date = "Fri Sep 02 15:42:26 CEST 2011")
public class JavaMethodDefinition_ extends JavaElement_ {
	
	public static volatile ListAttribute<JavaMethodDefinition, String> signature;
}
