/**
 * Generated by OpenJPA MetaModel Generator Tool.
 **/

package de.unisaarland.cs.st.moskito.ppa.model;

import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel (value = de.unisaarland.cs.st.moskito.ppa.model.JavaTypeDefinition.class)
@javax.annotation.Generated (value = "org.apache.openjpa.persistence.meta.AnnotationProcessor6",
                             date = "Fri Sep 02 15:42:26 CEST 2011")
public class JavaTypeDefinition_ extends JavaElement_ {
	
	public static volatile SingularAttribute<JavaTypeDefinition, Boolean>                                                    anonymClass;
	public static volatile SingularAttribute<JavaTypeDefinition, de.unisaarland.cs.st.moskito.ppa.model.JavaTypeDefinition> parent;
	public static volatile SingularAttribute<JavaTypeDefinition, String>                                                     superClassName;
}
