/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package de.unisaarland.cs.st.moskito.ppa.model;

import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=de.unisaarland.cs.st.moskito.ppa.model.JavaElement.class)
@javax.annotation.Generated
(value="org.apache.openjpa.persistence.meta.AnnotationProcessor6",date="Fri Sep 02 15:42:26 CEST 2011")
public class JavaElement_ {
    public static volatile SingularAttribute<JavaElement,String> elementType;
    public static volatile SingularAttribute<JavaElement,String> fullQualifiedName;
    public static volatile SingularAttribute<JavaElement,Long> generatedId;
}
