/**
 * Generated by OpenJPA MetaModel Generator Tool.
 **/

package org.mozkito.mappings.mappable.model;

import javax.persistence.metamodel.SingularAttribute;

/**
 * The Class MappableEntity_.
 */
@javax.persistence.metamodel.StaticMetamodel (value = org.mozkito.mappings.mappable.model.MappableEntity.class)
@javax.annotation.Generated (value = "org.apache.openjpa.persistence.meta.AnnotationProcessor6",
                             date = "Thu Nov 03 18:46:07 CET 2011")
public class MappableEntity_ {
	
	/** The generated id. */
	public static volatile SingularAttribute<MappableEntity, Long> generatedId;
}
