/**
 * Generated by OpenJPA MetaModel Generator Tool.
 **/

package org.mozkito.mappings.mappable.model;

import javax.persistence.metamodel.SingularAttribute;

import org.mozkito.versions.model.RCSTransaction;


/**
 * The Class MappableTransaction_.
 */
@javax.persistence.metamodel.StaticMetamodel (value = org.mozkito.mappings.mappable.model.MappableTransaction.class)
@javax.annotation.Generated (value = "org.apache.openjpa.persistence.meta.AnnotationProcessor6",
                             date = "Thu Nov 03 18:48:56 CET 2011")
public class MappableTransaction_ extends MappableEntity_ {
	
	/** The transaction. */
	public static volatile SingularAttribute<MappableTransaction, RCSTransaction> transaction;
}
