/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package de.unisaarland.cs.st.moskito.mapping.model;

import javax.persistence.metamodel.CollectionAttribute;
import javax.persistence.metamodel.MapAttribute;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=de.unisaarland.cs.st.moskito.mapping.model.Mapping.class)
@javax.annotation.Generated
(value="org.apache.openjpa.persistence.meta.AnnotationProcessor6",date="Wed Jan 18 19:05:50 CET 2012")
public class Mapping_ {
    public static volatile SingularAttribute<Mapping,String> class1;
    public static volatile SingularAttribute<Mapping,String> class2;
    public static volatile CollectionAttribute<Mapping,MappingEngineFeature> features;
    public static volatile SingularAttribute<Mapping,String> fromId;
    public static volatile MapAttribute<Mapping,String,Boolean> strategies;
    public static volatile SingularAttribute<Mapping,String> toId;
    public static volatile SingularAttribute<Mapping,Double> totalConfidence;
}
