/**
 * Generated by OpenJPA MetaModel Generator Tool.
 **/

package de.unisaarland.cs.st.moskito.mapping.model;

import javax.persistence.metamodel.ListAttribute;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel (value = de.unisaarland.cs.st.moskito.mapping.model.PersistentMapping.class)
@javax.annotation.Generated (value = "org.apache.openjpa.persistence.meta.AnnotationProcessor6",
                             date = "Fri Sep 02 15:37:56 CEST 2011")
public class PersistentMapping_ {
	
	public static volatile SingularAttribute<PersistentMapping, MapScore> score;
	public static volatile ListAttribute<PersistentMapping, String>       strategies;
	public static volatile SingularAttribute<PersistentMapping, Boolean>  valid;
}
