/**
 * Generated by OpenJPA MetaModel Generator Tool.
 **/

package de.unisaarland.cs.st.mozkito.persistence.model;

import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel (value = de.unisaarland.cs.st.mozkito.persistence.model.EnumTuple.class)
@javax.annotation.Generated (value = "org.apache.openjpa.persistence.meta.AnnotationProcessor6",
                             date = "Fri Sep 02 15:41:15 CEST 2011")
public class EnumTuple_ {
	
	public static volatile SingularAttribute<EnumTuple, String> enumClassName;
	public static volatile SingularAttribute<EnumTuple, String> newStringValue;
	public static volatile SingularAttribute<EnumTuple, String> oldStringValue;
}
