/*******************************************************************************
 * Copyright 2011 Kim Herzig, Sascha Just
 * 
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 * 
 * http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
 * an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations under the License.
 *****************************************************************************/
package org.mozkito.mappings.model;

import java.util.HashSet;
import java.util.LinkedList;
import java.util.Set;

import javax.persistence.ElementCollection;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.persistence.Transient;

import net.ownhero.dev.ioda.Tuple;
import net.ownhero.dev.kanuni.conditions.CompareCondition;
import net.ownhero.dev.kanuni.conditions.Condition;

import org.mozkito.mappings.finder.Finder;
import org.mozkito.mappings.mappable.model.MappableEntity;
import org.mozkito.mappings.selectors.Selector;
import org.mozkito.persistence.Annotated;

/**
 * This class represents a potential mapping pair and thus encapsulates to {@link MappableEntity}s. {@link Candidate}s
 * are generated by the {@link Finder} class using {@link Finder#getCandidates(MappableEntity, Class)}.
 * 
 * @author Sascha Just <sascha.just@mozkito.org>
 * 
 */
@Entity
public class Candidate implements Annotated {
	
	/** The Constant serialVersionUID. */
	private static final long serialVersionUID = 1464864624834219097L;
	
	/** the entity under subject. */
	private MappableEntity    from;
	
	/** The preselectors. */
	private Set<String>       selectors        = new HashSet<String>();
	
	/** a potential target. */
	private MappableEntity    to;
	
	/** The generated id. */
	private long              generatedId;
	
	/**
	 * Instantiates a new candidate.
	 */
	@Deprecated
	public Candidate() {
		// for OpenJPA only
	}
	
	/**
	 * Instantiates a new candidate.
	 * 
	 * @param candidatePair
	 *            a {@link Tuple} representing the pair (from/to)
	 */
	public Candidate(final Tuple<? extends MappableEntity, ? extends MappableEntity> candidatePair) {
		this.from = candidatePair.getFirst();
		this.to = candidatePair.getSecond();
	}
	
	/*
	 * (non-Javadoc)
	 * @see org.mozkito.mappings.model.ICandidate#addSelector(org.mozkito.mappings.selectors.Selector)
	 */
	/**
	 * Adds the selector.
	 * 
	 * @param selector
	 *            the selector
	 * @return true, if successful
	 */
	@Transient
	public boolean addSelector(final Selector selector) {
		return this.selectors.add(selector.getHandle());
	}
	
	/**
	 * Adds the selectors.
	 * 
	 * @param selectors
	 *            the selectors
	 */
	@Transient
	public void addSelectors(final Set<Selector> selectors) {
		// PRECONDITIONS
		
		try {
			for (final Selector selector : selectors) {
				addSelector(selector);
			}
		} finally {
			// POSTCONDITIONS
		}
	}
	
	/*
	 * (non-Javadoc)
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@Override
	@Transient
	public boolean equals(final Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		final Candidate other = (Candidate) obj;
		if (this.from == null) {
			if (other.from != null) {
				return false;
			}
		} else if (!this.from.equals(other.from)) {
			return false;
		}
		if (this.to == null) {
			if (other.to != null) {
				return false;
			}
		} else if (!this.to.equals(other.to)) {
			return false;
		}
		return true;
	}
	
	/*
	 * (non-Javadoc)
	 * @see org.mozkito.mappings.model.ICandidate#getClass1()
	 */
	/**
	 * Gets the class1.
	 * 
	 * @return the class1
	 */
	@Transient
	public String getClass1() {
		// PRECONDITIONS
		
		try {
			return getFrom().getBaseType().getCanonicalName();
		} finally {
			// POSTCONDITIONS
		}
	}
	
	/*
	 * (non-Javadoc)
	 * @see org.mozkito.mappings.model.ICandidate#getClass2()
	 */
	/**
	 * Gets the class2.
	 * 
	 * @return the class2
	 */
	@Transient
	public String getClass2() {
		// PRECONDITIONS
		
		try {
			return getTo().getBaseType().getCanonicalName();
		} finally {
			// POSTCONDITIONS
		}
	}
	
	/*
	 * (non-Javadoc)
	 * @see org.mozkito.mappings.model.ICandidate#getFrom()
	 */
	/**
	 * Gets the from.
	 * 
	 * @return the from
	 */
	@ManyToOne (fetch = FetchType.EAGER, cascade = {})
	public final MappableEntity getFrom() {
		return this.from;
	}
	
	/**
	 * Gets the generated id.
	 * 
	 * @return the generated id
	 */
	@Id
	@GeneratedValue
	public long getGeneratedId() {
		return this.generatedId;
	}
	
	/**
	 * Gets the simple name of the class.
	 * 
	 * @return the simple name of the class.
	 */
	@Transient
	public final String getHandle() {
		// PRECONDITIONS
		
		final StringBuilder builder = new StringBuilder();
		
		try {
			final LinkedList<Class<?>> list = new LinkedList<Class<?>>();
			Class<?> clazz = getClass();
			list.add(clazz);
			
			while ((clazz = clazz.getEnclosingClass()) != null) {
				list.addFirst(clazz);
			}
			
			for (final Class<?> c : list) {
				if (builder.length() > 0) {
					builder.append('.');
				}
				
				builder.append(c.getSimpleName());
			}
			
			return builder.toString();
		} finally {
			// POSTCONDITIONS
			Condition.notNull(builder,
			                  "Local variable '%s' in '%s:%s'.", "builder", getClass().getSimpleName(), "getHandle()"); //$NON-NLS-1$ //$NON-NLS-2$ //$NON-NLS-3$
		}
	}
	
	/**
	 * Gets the selectors.
	 * 
	 * @return the votingSelectors
	 */
	@ElementCollection
	public final Set<String> getSelectors() {
		// PRECONDITIONS
		
		try {
			return this.selectors;
		} finally {
			// POSTCONDITIONS
			Condition.notNull(this.selectors, "Field '%s' in '%s'.", "votingSelectors", //$NON-NLS-1$ //$NON-NLS-2$
			                  getClass().getSimpleName());
		}
	}
	
	/*
	 * (non-Javadoc)
	 * @see org.mozkito.mappings.model.ICandidate#getTo()
	 */
	/**
	 * Gets the to.
	 * 
	 * @return the to
	 */
	@ManyToOne (fetch = FetchType.EAGER, cascade = {})
	public final MappableEntity getTo() {
		return this.to;
	}
	
	/*
	 * (non-Javadoc)
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	@Transient
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = (prime * result) + ((this.from == null)
		                                                ? 0
		                                                : this.from.hashCode());
		result = (prime * result) + ((this.to == null)
		                                              ? 0
		                                              : this.to.hashCode());
		return result;
	}
	
	/**
	 * Sets the from.
	 * 
	 * @param from
	 *            the from to set
	 */
	public void setFrom(final MappableEntity from) {
		// PRECONDITIONS
		Condition.notNull(from, "Argument '%s' in '%s'.", "from", getClass().getSimpleName()); //$NON-NLS-1$ //$NON-NLS-2$
		
		try {
			this.from = from;
		} finally {
			// POSTCONDITIONS
			CompareCondition.equals(this.from, from,
			                        "After setting a value, the corresponding field has to hold the same value as used as a parameter within the setter."); //$NON-NLS-1$
		}
	}
	
	/**
	 * Sets the generated id.
	 * 
	 * @param generatedId
	 *            the generatedId to set
	 */
	public void setGeneratedId(final long generatedId) {
		// PRECONDITIONS
		Condition.notNull(generatedId, "Argument '%s' in '%s'.", "generatedId", getClass().getSimpleName());
		
		try {
			this.generatedId = generatedId;
		} finally {
			// POSTCONDITIONS
			CompareCondition.equals(this.generatedId, generatedId,
			                        "After setting a value, the corresponding field has to hold the same value as used as a parameter within the setter.");
		}
	}
	
	/**
	 * Sets the selectors.
	 * 
	 * @param selectors
	 *            the selectors to set
	 */
	public void setSelectors(final Set<String> selectors) {
		// PRECONDITIONS
		Condition.notNull(selectors, "Argument '%s' in '%s'.", "selectors", getClass().getSimpleName()); //$NON-NLS-1$ //$NON-NLS-2$
		
		try {
			this.selectors = selectors;
		} finally {
			// POSTCONDITIONS
			CompareCondition.equals(this.selectors, selectors,
			                        "After setting a value, the corresponding field has to hold the same value as used as a parameter within the setter."); //$NON-NLS-1$
		}
	}
	
	/**
	 * Sets the to.
	 * 
	 * @param to
	 *            the to to set
	 */
	public void setTo(final MappableEntity to) {
		// PRECONDITIONS
		Condition.notNull(to, "Argument '%s' in '%s'.", "to", getClass().getSimpleName()); //$NON-NLS-1$ //$NON-NLS-2$
		
		try {
			this.to = to;
		} finally {
			// POSTCONDITIONS
			CompareCondition.equals(this.to, to,
			                        "After setting a value, the corresponding field has to hold the same value as used as a parameter within the setter."); //$NON-NLS-1$
		}
	}
	
	/*
	 * (non-Javadoc)
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		final StringBuilder builder = new StringBuilder();
		
		builder.append(getHandle());
		builder.append(" [from="); //$NON-NLS-1$
		builder.append(this.from);
		builder.append(", to="); //$NON-NLS-1$
		builder.append(this.to);
		builder.append("]"); //$NON-NLS-1$
		return builder.toString();
	}
}
