/*******************************************************************************
 * Copyright 2011 Kim Herzig, Sascha Just
 * 
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 * 
 * http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
 * an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations under the License.
 *****************************************************************************/
package org.mozkito.mappings.model;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Id;
import javax.persistence.Transient;

import net.ownhero.dev.ioda.Tuple;

import org.mozkito.mappings.finder.Finder;
import org.mozkito.mappings.mappable.model.MappableEntity;
import org.mozkito.mappings.selectors.Selector;
import org.mozkito.persistence.Annotated;

/**
 * This class represents a potential mapping pair and thus encapsulates to {@link MappableEntity}s. {@link Candidate}s
 * are generated by the {@link Finder} class using {@link Finder#getCandidates(MappableEntity, Class)}.
 * 
 * @author Sascha Just <sascha.just@mozkito.org>
 * 
 */
public class Candidate implements Annotated, ICandidate {
	
	/** The Constant serialVersionUID. */
	private static final long    serialVersionUID = 1464864624834219097L;
	
	/** the entity under subject. */
	private final MappableEntity from;
	
	/** The preselectors. */
	private final Set<String>    selectors        = new HashSet<>();
	
	/** a potential target. */
	private final MappableEntity to;
	
	/**
	 * Instantiates a new candidate.
	 * 
	 * @param candidatePair
	 *            a {@link Tuple} representing the pair (from/to)
	 * @param selectors
	 *            the selectors
	 */
	public Candidate(final Tuple<? extends MappableEntity, ? extends MappableEntity> candidatePair,
	        final Set<Selector> selectors) {
		this.from = candidatePair.getFirst();
		this.to = candidatePair.getSecond();
		
		for (final Selector selector : selectors) {
			this.selectors.add(selector.getHandle());
		}
	}
	
	/*
	 * (non-Javadoc)
	 * @see org.mozkito.mappings.model.ICandidate#addSelector(org.mozkito.mappings.selectors.Selector)
	 */
	@Override
	@Transient
	public boolean addSelector(final Selector selector) {
		return this.selectors.add(selector.getHandle());
	}
	
	/*
	 * (non-Javadoc)
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	
	@Override
	@Transient
	public boolean equals(final Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		final Candidate other = (Candidate) obj;
		if (this.from == null) {
			if (other.from != null) {
				return false;
			}
		} else if (!this.from.equals(other.from)) {
			return false;
		}
		if (this.to == null) {
			if (other.to != null) {
				return false;
			}
		} else if (!this.to.equals(other.to)) {
			return false;
		}
		return true;
	}
	
	/*
	 * (non-Javadoc)
	 * @see org.mozkito.mappings.model.ICandidate#getClass1()
	 */
	@Override
	public String getClass1() {
		// PRECONDITIONS
		
		try {
			return getFrom().getBaseType().getCanonicalName();
		} finally {
			// POSTCONDITIONS
		}
	}
	
	/*
	 * (non-Javadoc)
	 * @see org.mozkito.mappings.model.ICandidate#getClass2()
	 */
	@Override
	public String getClass2() {
		// PRECONDITIONS
		
		try {
			return getTo().getBaseType().getCanonicalName();
		} finally {
			// POSTCONDITIONS
		}
	}
	
	/*
	 * (non-Javadoc)
	 * @see org.mozkito.mappings.model.ICandidate#getFrom()
	 */
	@Override
	@Id
	public final MappableEntity getFrom() {
		return this.from;
	}
	
	/*
	 * (non-Javadoc)
	 * @see org.mozkito.mappings.model.ICandidate#getTo()
	 */
	@Override
	@Id
	public final MappableEntity getTo() {
		return this.to;
	}
	
	/*
	 * (non-Javadoc)
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	@Transient
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = (prime * result) + ((this.from == null)
		                                                ? 0
		                                                : this.from.hashCode());
		result = (prime * result) + ((this.to == null)
		                                              ? 0
		                                              : this.to.hashCode());
		return result;
	}
	
	/*
	 * (non-Javadoc)
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		final StringBuilder stringBuilder = new StringBuilder();
		stringBuilder.append("Candidate [from="); //$NON-NLS-1$
		stringBuilder.append(this.from);
		stringBuilder.append(", to="); //$NON-NLS-1$
		stringBuilder.append(this.to);
		stringBuilder.append("]"); //$NON-NLS-1$
		return stringBuilder.toString();
	}
}
