/**
 * Generated by OpenJPA MetaModel Generator Tool.
 **/

package org.mozkito.mappings.model;

import javax.persistence.metamodel.MapAttribute;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel (value = org.mozkito.mappings.model.Composite.class)
@javax.annotation.Generated (value = "org.apache.openjpa.persistence.meta.AnnotationProcessor6",
                             date = "Mon Nov 05 13:24:42 CET 2012")
public class Composite_ {
	
	public static volatile SingularAttribute<Composite, Relation>   relation;
	public static volatile MapAttribute<Composite, String, Boolean> strategies;
}
