/**
 * Generated by OpenJPA MetaModel Generator Tool.
 **/

package org.mozkito.mappings.model;

import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel (value = org.mozkito.mappings.model.Feature.class)
@javax.annotation.Generated (value = "org.apache.openjpa.persistence.meta.AnnotationProcessor6",
                             date = "Mon Nov 05 13:24:42 CET 2012")
public class Feature_ {
	
	public static volatile SingularAttribute<Feature, Double> confidence;
	public static volatile SingularAttribute<Feature, String> fqClassName;
	public static volatile SingularAttribute<Feature, String> fromFieldName;
	public static volatile SingularAttribute<Feature, String> fromSubstring;
	public static volatile SingularAttribute<Feature, String> toFieldName;
	public static volatile SingularAttribute<Feature, String> toSubstring;
}
