/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package org.mozkito.mappings.model;

import javax.persistence.metamodel.SetAttribute;
import javax.persistence.metamodel.SingularAttribute;
import org.mozkito.issues.tracker.model.Report;
import org.mozkito.versions.model.RCSFile;

@javax.persistence.metamodel.StaticMetamodel
(value=org.mozkito.mappings.model.File2Bugs.class)
@javax.annotation.Generated
(value="org.apache.openjpa.persistence.meta.AnnotationProcessor6",date="Mon Nov 05 10:34:15 CET 2012")
public class File2Bugs_ {
    public static volatile SingularAttribute<File2Bugs,RCSFile> file;
    public static volatile SetAttribute<File2Bugs,Report> reports;
}
