/**
 * Generated by OpenJPA MetaModel Generator Tool.
 **/

package org.mozkito.mappings.model;

import javax.persistence.metamodel.MapAttribute;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel (value = org.mozkito.mappings.model.Mapping.class)
@javax.annotation.Generated (value = "org.apache.openjpa.persistence.meta.AnnotationProcessor6",
                             date = "Mon Nov 05 13:24:42 CET 2012")
public class Mapping_ {
	
	public static volatile SingularAttribute<Mapping, Composite>  composite;
	public static volatile MapAttribute<Mapping, String, Boolean> filters;
}
