/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package org.mozkito.mappings.model;

import javax.persistence.metamodel.CollectionAttribute;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=org.mozkito.mappings.model.Relation.class)
@javax.annotation.Generated
(value="org.apache.openjpa.persistence.meta.AnnotationProcessor6",date="Mon Nov 05 10:34:15 CET 2012")
public class Relation_ {
    public static volatile SingularAttribute<Relation,Candidate> candidate;
    public static volatile CollectionAttribute<Relation,Feature> features;
    public static volatile SingularAttribute<Relation,Long> generatedId;
}
